name: publish
on:
  push:
    tags:
      - 'v*'
permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v5
      - name: publish
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: 'v1'
          args: release --clean