name: Unit Test
on:
  push:
    branches:
      - main
      - release/*
    tags:
      - 'v*'
      - 'release'
  pull_request:
    branches:
      - main
      - release/*
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
      - run: mkdir vendor
      - name: tidy and vendor
        run: |
          go mod tidy
          go mod vendor
        env:
          GO111MODULE: on
      - name: Test with the Go CLI
        run: go test -v ./...
        working-directory: ${{ github.workspace }}
        env:
          CGO_ENABLED: 0
          GO111MODULE: on